services:
  tailscale-samba:
    image: tailscale/tailscale:latest
    container_name: tailscale-samba
    hostname: main-nas
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    env_file:
      - .env
    volumes:
      - /srv/docker/nas/tailscale/config:/etc/tailscale
      - /srv/docker/nas/tailscale/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
  samba:
    image: dockurr/samba:latest
    container_name: samba
    restart: always
    environment:
      - NAME=Share
    volumes:
      - /media/andreamnt94/Storage:/storage
    network_mode: service:tailscale-samba
